//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Sh.Core.Locales {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Translations() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp.Sh.Core.Locales.Translations", typeof(Translations).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Clientele Url cannot be null or empty.
        /// </summary>
        public static string Clientele_NotNull {
            get {
                return ResourceManager.GetString("Clientele_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Company cannot be null or empty.
        /// </summary>
        public static string Company_NotNull {
            get {
                return ResourceManager.GetString("Company_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Service Hub Url cannot be null or empty.
        /// </summary>
        public static string Hub_NotNull {
            get {
                return ResourceManager.GetString("Hub_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The OData Url cannot be null or empty.
        /// </summary>
        public static string Odata_NotNull {
            get {
                return ResourceManager.GetString("Odata_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The StartDate cannot be null or empty.
        /// </summary>
        public static string StartDate_NotNull {
            get {
                return ResourceManager.GetString("StartDate_NotNull", resourceCulture);
            }
        }
    }
}
